### ISSUE TITLE
Button Navigation doesn’t work

### ISSUE THREAD

**Issue by alaminkawsar** [shahadatrucse/Book_Store#1]
Look at your button navigation

**Comment by shahadatrucse** [comment]
Sajeeb Project:   https://github.com/SajeebChakraborty/CRUD-Seeding-PDF-Search-laravel?fbclid=IwAR3esyT4kNgIeuQsnB70UbxmAkPajno4dzeKAuKqcPax4FW9ZSfOCbX9AdY
